export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-sgma-beige via-sgma-beige/40 to-sgma-beige/10 relative text-sgma-charcoal pt-12 pb-12">
      <div className="py-8 px-4 relative z-10">
        <div className="max-w-4xl mx-auto">
          {/* Page Header */}
          <div className="mb-12 text-center">
            <h1 className="text-h1 md:text-display-sm font-black mb-4 uppercase tracking-tight text-sgma-charcoal">
              Terms and Conditions
            </h1>
            <p className="text-sgma-charcoal/70 text-caption">
              Effective Date: November 2025 • Last Updated: November 2025
            </p>
          </div>

          {/* Content */}
          <div className="prose prose-sm max-w-none text-sgma-charcoal">
            {/* Section 1: Introduction */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Introduction
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              This website under the name and style "SGMA - Sacred Geometry Mandala Art" and available at sacredgeometry.in, is owned, operated, and made available by Antya Web Pvt Ltd, with its registered office situated at 3/3, First Floor, Corporation Colony Street, Kodambakkam, Chennai-600024 and includes any of our affiliates, associates, assignees or successors-in-interest as determined by us at our sole discretion and without requiring any prior notice or intimation ("Company", "we" or "us" or "our") to the person accessing, viewing or using the Website ("You" or "Your" or "User").
            </p>

            <p className="mb-6 leading-relaxed text-body">
              Please read these terms and conditions ("Terms and Conditions") along with the Company's privacy policy available at Privacy Policy and all other rules and policies made available or published on the Website as they shall govern Your use of the Website and the Services (defined below) provided thereunder.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              Please note that You must be at least 18 (eighteen) years old to access, register on the Website and avail the Services. In case You represent an entity or an Institution (defined below), You hereby confirm that You have been duly authorized by such entity or Institution and further confirm that You are 18 (eighteen) years old or above and that You have the authority and all necessary approvals to enter into these Terms and Conditions and the Privacy Policy. If You are a Child, You are not permitted to access or register on this Website unless such access and registration is completed by a parent or legal guardian or the Instructor (defined below) as applicable. We may, in our sole discretion, refuse to offer the Service (defined below) to any person or entity and change the eligibility criteria at any time. Anyone below 18 (eighteen) years of age is assumed to be a child ("Child") and requires parental consent to use the Website. The parents/legal guardian of the Child or users above 18 (eighteen) years of age are hereinafter referred to as "You" or "Your".
            </p>

            <p className="mb-6 leading-relaxed text-body">
              The Website's privacy practices regarding the collection, use and safeguard of Your information including any personal and sensitive personal information shall be governed by the Company's Privacy Policy.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              By using or visiting the Website, You confirm Your agreement to these Terms and Conditions and the Privacy Policy.
            </p>

            <p className="mb-8 leading-relaxed font-semibold bg-sgma-navy/5 border-l-4 border-sgma-cta px-4 py-3 text-body">
              These Terms and Conditions are an electronic record as per the Information Technology Act, 2000 (as amended / re-enacted) and rules thereunder and is published in accordance with the provisions of Rule 3 (1)(b) of the of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021, which mandates for publishing of rules and regulations, privacy policy and terms and conditions for access or usage of any application or website. This electronic record is generated by a computer system.
            </p>

            {/* Section 2: Acceptance of Terms */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Acceptance of Terms
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              By downloading and/or by registering or signing up for the Services, or otherwise having access to, receiving, and/or using the Website, You represent and warrant to the Company that You have the right, authority and capacity to use the Website. You acknowledge to have read, understood and consented to be governed and bound by these Terms and Conditions and the Privacy Policy. If You do not accept or agree to any part of these Terms and Conditions or the Privacy Policy, please refrain from using the Website or the Services. Please note that You must be at least 18 (eighteen) years old to accept these Terms and Conditions. If You are a Child, Your acceptance will not be approved unless such acceptance is completed by a parent or legal guardian or an Instructor (as applicable).
            </p>

            {/* Section 3: Overview of the Services */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Overview of the Services
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              We as an intermediary make available certain features and tools that enable the Instructors to interact, work with and mentor the Students (defined below) through various digital learning solutions such as video conferencing in order to provide such Students with tutorial, educational and other education-related services ("Services"). The Website is a platform through which You can obtain information about us and our Services. You may use the Website to subscribe to the Services in accordance with the Terms and Conditions and the Privacy Policy.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              The Website allows teachers, mentors and instructors to subscribe to our Services which further enables them to share, access, and provide various educational content including sessions, classes, lectures and webinars ("Instructors") to various students across the globe who have subscribed to our Services to receive such educational content ("Students").
            </p>

            <p className="mb-6 leading-relaxed text-body">
              As part of the Services, we also enable users of the Website to access various Company Materials (defined below) as may be provided by us on the Website from time to time. These Terms and Conditions apply to all Your and/or Your Child's activities on the Website, our mobile application, other related services and platform as communicated to You by us from time to time.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              Please note that we only act as an intermediary between the Instructors and the Students for the provision of Services. Any services provided by the Instructors shall be provided on an "as is" basis and we shall not be made responsible and/or liable for any performance and obligation of the Instructors including any warranty for the services being provided by such Instructors.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              Additionally, as part of the Services, there are currently educational courses on various subjects offered by us, and depending upon the course module selected by You, we grant You access to the course module's material, content, curriculum, documents and other information and data ("Company Material") which may be in the form of video, audio, written, graphic, recorded, photographic, or any other format as may be prescribed and provided by us. Upon availing of the Services, we grant You a limited, non-transferable, non-exclusive and revocable license to access, view and use the Website, the Services and the Company Material for non-commercial purposes only. Any rights not expressly granted to You herein are reserved by the Company. You shall abide by and maintain all copyright notices, information, and restrictions contained in any such Company Material. It is hereby clarified that such Company Material is provided by third parties and that the Company does not monitor, curate, edit or has any control over such Company Material. All Company Material is made available on an "as is" and "as available" basis and without any representations or warranties whatsoever, and the Company hereby disclaims any implied warranties, including but not limited to warranties of fitness for use, accuracy, merchantability, and non-infringement.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              It is further clarified that access to the Services under this Clause is for a limited period of time as communicated by us on the Website from time to time and any payment of Fees (defined below) under Clause 7 does not entitle You or Your Child to unlimited access to the Services and/or the Company Materials.
            </p>

            {/* Section 4: Access */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Access
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              Subject to these Terms and Conditions and the Privacy Policy, we offer to provide the Services, which are selected by You, solely for Your benefit, and not for the use or benefit of any third party.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              If there is any particular content You wish to procure from the Website pertaining to any Service, You may be required to send us an email from Your registered email-id, requesting us for access to such content. You agree and acknowledge that grant of any such request shall be at the sole discretion of the Company.
            </p>

            {/* Section 5: Registration and Eligibility */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Registration and Eligibility
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              In order to use and avail the Services, You are required to register with us by providing personal information relating to You and/or the Child, and covenant that You shall provide us with accurate, correct and complete registration information including but not limited to, (i) Your and/or the Child's name, (ii) Your e-mail ID, (iii) Your contact details (iv) payment information of the Fees for the Services, if required and (v) any other documents as required under applicable laws and communicated to You on the Website from time to time. You shall follow the registration process as communicated to You on the Website from time to time. You shall ensure that the requisite information provided by You to us for the Services, is absolutely true, up-to-date and correct and nothing material has been concealed, and that You agree to maintain the accuracy of such information. We will not be liable for any incident occurring due to incorrect or insufficient information provided by You.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              You acknowledge that Your user ID and password for the Website ("Login Details") is for Your exclusive use only. You are solely responsible and liable for any activity that occurs on Your account and You shall not use or share Your Login Details with another user or person. It is hereby clarified that any contravention of this Clause is cause for immediate suspension of Your access to the Website, the Services and the content including Company Materials provided by us. You agree to immediately notify and update us in the event there is any change in Your Login Details and further covenant to keep us updated at all times.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              You are solely responsible for maintaining the confidentiality of Your Login Details and for all activities that occur under it. You agree to immediately notify us if You become aware of or have reason to believe that there is any unauthorized use of Your Login Details. You also agree to take all necessary steps to stop such unauthorized use and to cooperate with us in any investigation of such unauthorized use. We shall not under any circumstances be held liable for any claims related to the use or misuse of Your Login Details due to the activities of any third party outside of our control or due to Your failure to maintain the confidentiality and security of Your Login Details.
            </p>

            {/* Section 6: Fees and Payment Terms */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Fees and Payment Terms
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              The Services may require payment of certain fees ("Fees"). You shall be notified of such Fees at the time of subscribing to our Services. You agree to pay the applicable Fees for the Services that You select. The Company reserves the right to change its price list and to institute new charges at any time, upon notice to You, which may be sent by email or posted on the Website. Your use of the Services following such notification constitutes Your acceptance of any new or increased charges. Any Fees paid hereunder are non-refundable.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              The payment of the Fees will be made by You using any of the payment gateways prescribed by us on the Website or any other electronic payment mechanism as communicated to You from time to time. We reserve the right to use a third-party payment gateway or other payment processing companies to process payments made by You. All credit and debit card information shall be processed and stored through a third-party payment processor and the Company shall not store any credit and debit card information. It is hereby clarified that the Company shall not be responsible and/or liable for any failure or delay in processing Your payment as a consequence of incorrect information provided by You or a result of any technical or other error pertaining to any payment gateway or payment processing company.
            </p>

            {/* Section 7: Use of the Website and Services */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Use of the Website and Services
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              In connection with Your use of the Website and the Services, You warrant that You will not:
            </p>

            <ul className="list-disc list-inside mb-8 space-y-3 text-sgma-charcoal">
              <li>Violate any laws or intellectual property or proprietary rights;</li>
              <li>Engage in any activity which is harmful, threatening, defamatory, obscene, harassing, or racially, ethnically, or otherwise objectionable or offensive;</li>
              <li>Post or transmit any material that contains viruses, trojan horses, worms, time bombs, cancelbots or other computer programming routines that may damage or interfere with the Website or Services;</li>
              <li>Post, publish, transmit, reproduce, distribute or in any way exploit information or software obtained through the Services for commercial purposes (other than as expressly permitted by the provider of such information or software);</li>
              <li>Upload, post, e-mail or otherwise transmit any material that contains information, software or other material which violates or infringes upon the rights of others, including material which is an invasion of privacy or publicity rights or which is protected by copyright, trademark or other proprietary right, or derivative works with respect thereto, without first obtaining written permission from the owner or right holder;</li>
              <li>Use the Website or Services for any fraudulent or unlawful purpose;</li>
              <li>Reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of the Services, use of the Services, or access to the Services;</li>
              <li>Modify, adapt, translate, reverse engineer, decompile or disassemble any portion of the Website or Services;</li>
              <li>Remove any copyright, trademark or other proprietary rights notices contained in or on the Website or Services;</li>
              <li>Use any robot, spider, site search or retrieval application, or any other manual or automatic device or process to retrieve, index, data mine, or in any way reproduce or circumvent the navigational structure or presentation of the Website or its contents;</li>
              <li>Frame or mirror any part of the Website without our prior written authorization;</li>
              <li>Create user accounts by automated means or under false or fraudulent pretenses;</li>
              <li>Impersonate or misrepresent Your affiliation with any person or entity;</li>
              <li>Interfere with or disrupt the Website or servers or networks connected to the Website, or disobey any requirements, procedures, policies or regulations of networks connected to the Website.</li>
            </ul>

            <p className="mb-8 leading-relaxed text-body">
              We reserve the right to terminate Your access to the Services and/or the Website if we reasonably believe that You have violated or acted inconsistently with the letter or spirit of these Terms and Conditions.
            </p>

            {/* Section 8: Intellectual Property Rights */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Intellectual Property Rights
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              The Website and the Services, including all content, features and functionality thereof are owned by the Company and/or its licensors and are protected by copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. Nothing in these Terms and Conditions shall be construed to confer any license to any intellectual property rights belonging to the Company or any third party whether by estoppel, implication, or otherwise. Unless otherwise indicated, all logos, names, package designs and marks on the Website are trademarks and the property of the Company, its affiliates or licensors. The use or misuse of any trademark or any other materials, except as expressly provided herein, is strictly prohibited.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              Subject to Your compliance with these Terms and Conditions, we grant You a personal, non-exclusive, non-transferable, non-sublicensable, revocable and limited license to access and use the Website and the Services. This license is for the sole purpose of enabling You to use and enjoy the benefit of the Services as provided by the Company, and in the manner permitted by these Terms and Conditions. You shall not reproduce, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store or transmit any of the material on the Website, except as generally and ordinarily permitted through the Website according to these Terms and Conditions.
            </p>

            {/* Section 9: Third Party Content */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Third Party Content
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              The Company may provide third party content on the Website and may provide links to web pages and content of third parties (collectively the "Third Party Content") as a service to You. The Company does not monitor or have any control over any Third Party Content. The Company does not endorse or adopt any Third Party Content and can make no guarantee as to its accuracy or completeness. The Company does not represent or warrant the accuracy of any information contained in the Third Party Content and undertakes no responsibility to update or review the Third Party Content. Users use such Third Party Content contained therein at their own risk.
            </p>

            {/* Section 10: User Content */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              User Content
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              You may be able to post, upload, or otherwise contribute content to the Website, which may include text, images, audio, video, or other materials ("User Content"). You retain all ownership rights in Your User Content, but You grant the Company the following license: a worldwide, non-exclusive, royalty-free, perpetual, transferable and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display Your User Content in any media, now known or hereafter devised.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              You represent and warrant that: (i) You own or have the necessary licenses, rights, consents, and permissions to use and authorize the Company to use all copyright, trademark, trade secret, and any other proprietary or intellectual property rights in and to any and all User Content to enable inclusion and use of the User Content in the manner contemplated by the Website and these Terms and Conditions; and (ii) Your User Content, and Your posting of such User Content, does not and will not violate these Terms and Conditions or the rights of any third party.
            </p>

            {/* Section 11: Indemnity */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Indemnity
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              You hereby agree to indemnify, defend and hold harmless the Company and its officers, directors, employees, agents, partners, contractors, affiliates, representatives, attorneys, and third-party service providers ("Indemnified Parties") from and against any and all claims, demands, causes of action, actions, suits, proceedings, losses, damages, costs and expenses (including attorneys' fees and court costs), fines or liabilities of any kind, arising out of or relating to: (i) Your access to or use of the Website and/or the Services; (ii) Your violation of these Terms and Conditions or the Privacy Policy; (iii) Your violation of any applicable law or regulation; (iv) Your User Content; (v) any claim that Your User Content caused damage to, or infringed the rights of a third party; or (vi) any dispute between You and any third party.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              This defense and indemnification obligation will survive the termination of these Terms and Conditions and Your use of the Website and Services.
            </p>

            {/* Section 12: Disclaimer of Warranties */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Disclaimer of Warranties
            </h2>
            <p className="mb-6 leading-relaxed text-body font-semibold">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE WEBSITE AND THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>

            <p className="mb-6 leading-relaxed text-body font-semibold">
              THE COMPANY MAKES NO WARRANTY THAT: (i) THE SERVICES WILL MEET YOUR REQUIREMENTS; (ii) THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE ACCURATE OR RELIABLE; (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS; OR (v) ANY ERRORS IN THE PRODUCTS OR SERVICES WILL BE CORRECTED.
            </p>

            <p className="mb-6 leading-relaxed text-body font-semibold">
              YOU UNDERSTAND AND AGREE THAT ANY MATERIAL AND/OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT YOUR OWN DISCRETION AND RISK AND THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL AND/OR DATA.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM THE COMPANY OR THROUGH THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.
            </p>

            {/* Section 13: Limitation of Liability */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Limitation of Liability
            </h2>
            <p className="mb-6 leading-relaxed text-body font-semibold">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATING TO THE USE OF, OR INABILITY TO USE, THE SERVICES, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>

            <p className="mb-6 leading-relaxed text-body font-semibold">
              UNDER NO CIRCUMSTANCES WILL THE COMPANY BE RESPONSIBLE FOR ANY DAMAGE, LOSS OR INJURY RESULTING FROM HACKING, TAMPERING OR OTHER UNAUTHORIZED ACCESS OR USE OF THE SERVICES OR YOUR ACCOUNT OR THE INFORMATION CONTAINED THEREIN.
            </p>

            <p className="mb-6 leading-relaxed text-body font-semibold">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY: (i) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT; (ii) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO OR USE OF OUR SERVICES; (iii) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION STORED THEREIN; (iv) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SERVICES; (v) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE THAT MAY BE TRANSMITTED TO OR THROUGH OUR SERVICES BY ANY THIRD PARTY; (vi) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE THROUGH THE SERVICES; AND/OR (vii) USER CONTENT OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY.
            </p>

            <p className="mb-8 leading-relaxed text-body font-semibold">
              IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR SUPPLIERS BE LIABLE TO YOU FOR ANY CLAIMS, PROCEEDINGS, LIABILITIES, OBLIGATIONS, DAMAGES, LOSSES OR COSTS IN AN AMOUNT EXCEEDING THE AMOUNT YOU PAID TO THE COMPANY HEREUNDER OR INR 1,000.00, WHICHEVER IS GREATER.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              THIS LIMITATION OF LIABILITY SECTION APPLIES WHETHER THE ALLEGED LIABILITY IS BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR ANY OTHER BASIS, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION.
            </p>

            {/* Section 14: Termination */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Termination
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              The Company may terminate or suspend Your access to the Website and the Services immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              Upon termination, Your right to use the Services will immediately cease. If You wish to terminate Your account, You may simply discontinue using the Services.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              All provisions of these Terms and Conditions which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.
            </p>

            {/* Section 15: Confidentiality and Data Protection */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Confidentiality and Data Protection
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              The Company shall maintain the confidentiality of all information and/or data received from You including Your Personal Information in accordance with the Privacy Policy. However, You understand and agree that the Company may be required to disclose Your information to third parties including, without limitation, government authorities, payment processors, service providers, and other third parties as may be necessary to provide the Services. The Company will maintain adequate organizational and technical safeguards to protect Your Personal Information in accordance with applicable laws.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              You understand and agree that we may access, preserve and disclose Your information if required to do so by law or in good faith belief that such access, preservation or disclosure is reasonably necessary to: (i) comply with legal process; (ii) enforce these Terms and Conditions; (iii) respond to claims that any content violates the rights of third parties; (iv) respond to Your requests for customer service; or (v) protect the rights, property or personal safety of the Company, its users and the public.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              You further understand and agree that the technical processing and transmission of the Services, including Your Personal Information, may involve transmissions over various networks and changes to conform and adapt to technical requirements of connecting networks or devices. Additionally, by utilizing the Services, You understand, acknowledge and agree that internet transmissions are never completely private or secure and that any message or information You send using our Services may be read or intercepted by others, even if there is a special notice that a particular transmission is encrypted.
            </p>

            {/* Section 16: Governing Law */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Governing Law
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              A printed version of these Terms and Conditions, Privacy Policy and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to these Terms and Conditions and the Privacy Policy to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
            </p>

            {/* Section 17: Dispute Resolution */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Dispute Resolution
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              These Terms and Conditions along with the Privacy Policy shall be governed by and construed in accordance with the laws of India. For all purposes of these Terms and Conditions and the Privacy Policy, and subject to Clause below, the Parties' consent to the exclusive jurisdiction of courts located in Chennai, Tamil Nadu.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              Any controversies, conflicts, disputes and/or differences between the parties shall thereafter be resolved by arbitration in Chennai, Tamil Nadu in accordance with the Arbitration and Conciliation Act, 1996 for the time being in force, which rules are deemed to be incorporated by reference in this Clause. The tribunal shall consist of 1 (one) arbitrator mutually appointed by the parties. The language of the arbitration shall be English.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              The parties shall keep the arbitration confidential and not disclose to any person, other than those necessary to the proceedings, any information, transcripts or award unless required to do so by law. The decision of the arbitrator shall be final and binding on all the parties hereto.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              Use of the Service is not authorized in any jurisdiction that does not give effect to all provisions of these Terms and Conditions and Privacy Policy, including without limitation, this Clause.
            </p>

            {/* Section 18: Severability */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Severability
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              If any provision of these Terms and Conditions and the Privacy Policy is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that these Terms and Conditions and the Privacy Policy will otherwise remain in full force and effect and enforceable. The failure of either party to exercise, in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. Waiver of compliance in any particular instance does not mean that we will waive compliance in the future. In order for any waiver of compliance with these Terms and Conditions and the Privacy Policy to be binding, we must provide You with written notice of such waiver through one of our authorized representatives.
            </p>

            {/* Section 19: Modification of Terms and Conditions */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Modification of Terms and Conditions
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              We reserve the right, at our sole discretion, to modify or replace any of these Terms and Conditions and the Privacy Policy, or change, suspend, and discontinue the Services (including without limitation, the availability of any feature, database, or content) or its usage at any time by posting a notice or by sending You a notice through our Service or via email/contact details provided as Login Details. We may also impose limits on certain features and Services or restrict Your access to parts or all of the Services without notice or liability. It is Your responsibility to check these Terms and Conditions and the Privacy Policy periodically for changes. Your continued subscription and use of the Services following the posting of any changes to these Terms and Conditions and the Privacy Policy shall constitute as an acceptance of those changes.
            </p>

            {/* Section 20: Links To Third Party Websites And Advertisements */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Links To Third Party Websites And Advertisements
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              We retain the unfettered right to display any advertisements on the Website. Further, the Website may include links to third party advertisements and other websites / applications, whose terms and privacy practices may differ from those of ours. You are advised to use Your discretion while visiting such websites/applications or while providing any personal information on such websites/ applications, or while purchasing of any products or services on such websites/applications.
            </p>

            <p className="mb-6 leading-relaxed text-body">
              The inclusion of a link does not imply any endorsement by us of such third-party website, the website's provider, the information on the third-party website, or the quality of products or services provided on such websites. You hereby agree and acknowledge that any access of such websites / applications shall be at Your sole risk, and we shall not be liable for any losses sustained by You in this regard.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              If You access or submit personal information to any of those websites, such access and information will be governed by the terms of use and privacy policies of such third-party websites and we disclaim all responsibility or liability with respect to the terms and policies of such websites. You are hereby advised to carefully read the terms and privacy policy of any website that You may visit.
            </p>

            {/* Section 21: Miscellaneous */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Miscellaneous
            </h2>
            <p className="mb-6 leading-relaxed text-body">
              Unless otherwise specified in these Terms and Conditions and the Privacy Policy, all notices hereunder will be in writing and will be deemed to have been duly given when received or when receipt is electronically confirmed, if transmitted by e-mail.
            </p>

            <p className="mb-8 leading-relaxed text-body">
              In respect of these Terms and Conditions and the Privacy Policy and Your use of these Services, nothing in these Terms and Conditions and the Privacy Policy shall be deemed to grant any rights or benefits to any person, other than us and You, or entitle any third party to enforce any provision hereof, and it is agreed that we do not intend that any provision of these Terms and Conditions and the Privacy Policy should be enforceable by a third party as per any applicable law.
            </p>

            {/* Section 22: Contact */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Contact
            </h2>
            <p className="mb-8 leading-relaxed text-body">
              Should You have questions about these Terms and Conditions and the Privacy Policy or information collection, use and disclosure practices in relation to the Services, You may contact our Grievance Officer as per the details and manner prescribed in our Privacy Policy.
            </p>

            {/* Section 23: Grievance Officer */}
            <h2 className="text-h3 font-black mb-4 mt-8 uppercase tracking-tight text-sgma-navy">
              Grievance Officer
            </h2>
            <div className="bg-sgma-navy/5 border-l-4 border-sgma-cta rounded-lg px-6 py-4 mb-8">
              <p className="text-body font-semibold text-sgma-charcoal mb-2">
                Name: Bharanidharan Vishwanathan
              </p>
              <p className="text-body font-semibold text-sgma-charcoal">
                Email: bharani@thecrux.ai
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
